---
deployment:
  tasks:
    - export DEPLOYPATH=/home/utetezio/public_html/reports/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='cgi-bin' --exclude='.well-known' ./ $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;